In [108]:
import numpy as np
import tensorflow as tf
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, InputLayer

In [109]:
X = np.random.rand(200, 2) * 200
y = np.random.rand(200, 1)

for i in range(len(y)):
    y[i] = 1 if y[i] >= 0.5 else 0

In [110]:
print(f"Temperature Max, Min pre normalization: {np.max(X[:,0]):0.2f}, {np.min(X[:,0]):0.2f}")
print(f"Duration    Max, Min pre normalization: {np.max(X[:,1]):0.2f}, {np.min(X[:,1]):0.2f}")
normalized = tf.keras.layers.Normalization(axis=-1)
normalized.adapt(X)
Xn = normalized(X)
print(f"Temperature Max, Min post normalization: {np.max(Xn[:,0]):0.2f}, {np.min(Xn[:,0]):0.2f}")
print(f"Duration    Max, Min post normalization: {np.max(Xn[:,1]):0.2f}, {np.min(Xn[:,1]):0.2f}")

Temperature Max, Min pre normalization: 198.47, 0.02
Duration    Max, Min pre normalization: 199.22, 1.92
Temperature Max, Min post normalization: 1.80, -1.74
Duration    Max, Min post normalization: 1.70, -1.79


In [111]:
Xt = np.tile(Xn, (1000, 1))
Yt = np.tile(y, (1000, 1))
print(Xt.shape, Yt.shape)

(200000, 2) (200000, 1)


In [112]:
model = Sequential([InputLayer(input_shape=(2,)),
                    Dense(units=3, activation='sigmoid', name='layer1'),
                    Dense(units=1, activation='sigmoid', name='layer2')])

In [113]:
model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer1 (Dense)               (None, 3)                 9         
_________________________________________________________________
layer2 (Dense)               (None, 1)                 4         
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________


In [114]:
L1_num_params = 2 * 3 + 3   # W1 parameters  + b1 parameters
L2_num_params = 3 * 1 + 1   # W2 parameters  + b2 parameters
print("L1 params = ", L1_num_params, ", L2 params = ", L2_num_params  )

L1 params =  9 , L2 params =  4


In [115]:
w1, b1 = model.get_layer('layer1').get_weights()
w2, b2 = model.get_layer('layer2').get_weights()
print(f"W1{w1.shape}:\n", w1, f"\nb1{b1.shape}:", b1)
print(f"W2{w2.shape}:\n", w2, f"\nb2{b2.shape}:", b2)

W1(2, 3):
 [[-0.06768489  0.18088996  0.78317785]
 [-0.12807369  1.0231986  -0.19893688]] 
b1(3,): [0. 0. 0.]
W2(3, 1):
 [[-0.84697735]
 [-0.9019981 ]
 [ 0.7080864 ]] 
b2(1,): [0.]


In [116]:
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
)

model.fit(Xt, Yt, epochs=10)

Epoch 1/10
6250/6250 [==============================] - 8s 1ms/step - loss: 0.6877
Epoch 2/10
6250/6250 [==============================] - 7s 1ms/step - loss: 0.6867
Epoch 3/10
6250/6250 [==============================] - 7s 1ms/step - loss: 0.6857
Epoch 4/10
6250/6250 [==============================] - 7s 1ms/step - loss: 0.6847
Epoch 5/10
6250/6250 [==============================] - 7s 1ms/step - loss: 0.6833
Epoch 6/10
6250/6250 [==============================] - 7s 1ms/step - loss: 0.6819
Epoch 7/10
6250/6250 [==============================] - 7s 1ms/step - loss: 0.6809
Epoch 8/10
6250/6250 [==============================] - 7s 1ms/step - loss: 0.6800
Epoch 9/10
6250/6250 [==============================] - 7s 1ms/step - loss: 0.6793
Epoch 10/10
6250/6250 [==============================] - 7s 1ms/step - loss: 0.6785


In [117]:
w1, b1 = model.get_layer('layer1').get_weights()
w2, b2 = model.get_layer('layer2').get_weights()
print(f"W1{w1.shape}:\n", w1, f"\nb1{b1.shape}:", b1)
print(f"W2{w2.shape}:\n", w2, f"\nb2{b2.shape}:", b2)

W1(2, 3):
 [[-0.05533522  3.561302    1.4957016 ]
 [-1.3079035   4.3333755   0.5951597 ]] 
b1(3,): [-2.0846107 -1.4345965 -1.3029325]
W2(3, 1):
 [[-1.8834904]
 [-1.3389453]
 [ 1.7084315]] 
b2(1,): [0.15422508]


In [118]:
X_test = np.array([
    [200,13.9],  # positive example
    [50,25]])   # negative example
X_testn = normalized(X_test)
predictions = model.predict(X_testn)
print("predictions = \n", predictions)

predictions = 
 [[0.5333099]
 [0.3484334]]
